name: Deploy Vulnerable Application # workflow name

on:
  workflow_run:
    workflows: ["Static security Analysis"]
    types:
      - completed
jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_APP_NAME }} #Must be unique in Heroku
          heroku_email: ${{ vars.HEROKU_EMAIL }}
          branch: "master"
          usedocker: true
